name: Code Quality

on:
  - pull_request
  - push

jobs:
  coding-guidelines:
    name: Coding Guidelines (php-cs-fixer)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instal PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - name: Update dependencies with composer
        run: composer update --no-interaction --ansi --no-progress

      - name: Install php-cs-fixer with composer
        run: composer bin php-cs-fixer update --no-interaction --ansi --no-progress

      - name: Run php-cs-fixer
        run: vendor-bin/php-cs-fixer/vendor/bin/php-cs-fixer fix --diff --dry-run --show-progress=dots --using-cache=no --verbose

  type-checker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
        dependencies:
          - lowest
          - highest

    name: Type Check (PHP-${{ matrix.php-version }}:${{ matrix.dependencies }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: composer:v2

      - if: matrix.dependencies == 'highest'
        run: composer update --no-interaction --no-progress --ansi

      - if: matrix.dependencies == 'lowest'
        run: composer update --no-interaction --no-progress --ansi --prefer-lowest

      - name: Install psalm with composer
        run: composer bin psalm update --no-interaction --ansi --no-progress

      - name: Run vimeo/psalm on packages
        run: bin/psalm --php-version=${{ matrix.php-version }} --no-progress --shepherd --show-info=true --stats
