name: Docs Deploy

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-docs:
    name: Build & Deploy

    runs-on: ubuntu-latest

    steps:
      - id: branch_info
        name: Prepare branch info
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          BRANCH_NAME="${GITHUB_REF##refs/heads/}"
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=${BRANCH_NAME}"

      - id: tag_info
        name: Prepare tag info
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "deploy_tag_name=deploy-docs-${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "TAG_NAME=${TAG_NAME}"

      - id: dest_dir
        name: Determine DEST_DIR
        run: |
          if [ ! -z "${{ steps.tag_info.outputs.tag_name }}" ]; then \
            DEST_DIR=`echo ${{ steps.tag_info.outputs.tag_name }} | sed -e 's:^\([0-9]\+\.[0-9]\+\).*$:\1:'`; \
          elif [ ! -z "${{ steps.branch_info.outputs.branch_name }}" ]; then \
            DEST_DIR=${{ steps.branch_info.outputs.branch_name }}; \
          else \
            DEST_DIR=tmp; \
          fi
          echo "dest_dir=${DEST_DIR}" >> $GITHUB_OUTPUT
          echo "DEST_DIR=${DEST_DIR}"

      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Initialize Docker environment
        run: php docker/initialize

      - name: Build API docs
        run: docker/docs run --rm doctum build

      - name: Build user docs
        run: |
          docker/docs run --rm sphinx build
          rm -rf docs/build/html/.doctrees docs/build/html/.buildinfo

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          destination_dir: ./docs/${{ steps.dest_dir.outputs.dest_dir }}
          force_orphan: false
          tag_name: ${{ steps.tag_info.outputs.deploy_tag_name }}
          tag_message: "deployment of docs for ${{ steps.tag_info.outputs.tag_name }}"
          enable_jekyll: true
