name: Style Check

on:
  - pull_request
  - push

jobs:
  coding-guidelines:
    name: php-cs-fixer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Instal PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: none

      - name: Update dependencies with composer
        run: composer update --no-interaction --ansi --no-progress

      - name: Install php-cs-fixer with composer
        run: composer bin php-cs-fixer update --no-interaction --ansi --no-progress

      - name: Run php-cs-fixer
        run: vendor-bin/php-cs-fixer/vendor/bin/php-cs-fixer check --diff --show-progress=dots --using-cache=no --verbose
